laser_rate: 30.0
laser_range: 7.0

laser_height: 480

depth_scaling_factor: 1000.0
laser2body_R: [ 0.0,  0.0,  1.0,
               -1.0,  0.0,  0.0,
                0.0, -1.0,  0.0]
laser2body_p: [0.0, 0.0, 0.05]
